### PR TITLE
Remove pytorch_fft as the dependency.

### PR DESCRIPTION
**Pull request by pushkalkatara**
Recently fft was implemented in pytorch
Solves issue #14

### CODE REVIEW

**Comment by Cadene** [comment]
Thanks!

**Comment by Cadene** [comment]
Thanks!

**Comment by pushkalkatara** [comment]
Hi @Cadene Please update the pypi package also with the master branch.

**Comment by Cadene** [comment]
@pushkalkatara Uploaded on pypi! Thanks :)

https://pypi.org/project/block.bootstrap.pytorch/0.1.6/

**Comment by pushkalkatara** [comment]
Thanks :D

**Pull request merged**
